Lagoon code size limit (#367)
- Lagoon v0.5.0 is broken due to exceeding Ethereum smart contract size limit of 24k with few bytes
- Fix by getting patched Lagoon master
- Document bug compiling `TradingStrategyModuleV0` that we do not get contract size information currently with Foundry
- Fix various deployment issues related to the Lagoon versions and ABI changes over time

```
|-------------------------------------------------------+------------------+-------------------+--------------------+---------------------|
| Vault (src/v0.1.0/Vault.sol)                          | 22,861           | 23,156            | 1,715              | 25,996              |
|-------------------------------------------------------+------------------+-------------------+--------------------+---------------------|
| Vault (src/v0.2.0/Vault.sol)                          | 23,313           | 23,608            | 1,263              | 25,544              |
|-------------------------------------------------------+------------------+-------------------+--------------------+---------------------|
| Vault (src/v0.3.0/Vault.sol)                          | 23,479           | 23,774            | 1,097              | 25,378              |
|-------------------------------------------------------+------------------+-------------------+--------------------+---------------------|
| Vault (src/v0.4.0/Vault.sol)                          | 23,706           | 24,001            | 870                | 25,151              |
|-------------------------------------------------------+------------------+-------------------+--------------------+---------------------|
| Vault (src/v0.5.0/Vault.sol)                          | 24,643           | 24,938            | -67                | 24,214              |
|-------------------------------------------------------+------------------+-------------------+--------------------+---------------------|
| VaultHelper (test/VaultHelper.sol)                    | 98               | 124               | 24,478             | 49,028              |

```

```
(web3-ethereum-defi-py3.11) ➜  lagoon-v0 git:(main) ✗ forge create --broadcast --rpc-url http://localhost:21218 --private-key $PRIVATE_KEY src/v0.5.0/Vault.sol:Vault --constructor-args true   

[⠊] Compiling...
No files changed, compilation skipped
Error: server returned an error response: error code -32603: EVM error CreateContractSizeLimit
```